Nota_1=int(input('Digite a primeira nota: '))
Nota_2=int(input('Digite a segunda nota: '))
Nota_3=int(input('Digite a terceira nota: '))
Nota_4=int(input('Digite a quarta nota: '))
print(f'A média aritmética é {(Nota_1+Nota_2+Nota_3+Nota_4) / 4}')
